apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: mscjaime/my-python-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer  # Usa NodePort si no tienes LoadBalancer
  loadBalancerIP: 192.168.0.19
  selector:
    app: python-app
  ports:
    - port: 8080
      targetPort: 5000

