name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    # Asocia este job con el environment protegido
    environment:
      name: production
      # Puedes definir una URL si tu app ya está en producción
      url: https://mi-dominio.com 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mscjaime/my-python-app:latest
